import type { GroupTheme } from "@/types/Group";

export const themeColorMappings: { [k: string]: GroupTheme } = {
    defaultTheme: {
        primaryColor: "#F6BC0D",
        secondaryColor: "#BE392C",
        backgroundColor: "#F5F4F4",
        cardBackgroundColor: "#D9D9D9",
        cardItemColor: "#F3F3F3",
        fontColorV1: "#FFFFFF",
        fontColorV2: "#191919",
        fontColorV3: "#8A8A8A",
        fontColorLinks: "#7D7EAE",
        fontColorDisabled: "#6F6F6F",
        buttonHoverColor: "#FFFFFF",
        fontColorAlert: "#CC615B",
        fontColorSuccess: "#35BD00",
        wrongInvalidColor: "#B33B3B",
    },
    themeId1: {
        primaryColor: "#0091B9",
        secondaryColor: "#934588",
        backgroundColor: "#F5F4F4",
        cardBackgroundColor: "#D9D9D9",
        cardItemColor: "#F3F3F3",
        fontColorV1: "#FFFFFF",
        fontColorV2: "#191919",
        fontColorV3: "#8A8A8A",
        fontColorLinks: "#7D7EAE",
        fontColorDisabled: "#6F6F6F",
        buttonHoverColor: "#FFFFFF",
        fontColorAlert: "#CC615B",
        fontColorSuccess: "#35BD00",
        wrongInvalidColor: "#B33B3B",
    },
    themeId2: {
        primaryColor: "#02366E",
        secondaryColor: "#FA7511",
        backgroundColor: "#F5F4F4",
        cardBackgroundColor: "#D9D9D9",
        cardItemColor: "#F3F3F3",
        fontColorV1: "#FFFFFF",
        fontColorV2: "#191919",
        fontColorV3: "#8A8A8A",
        fontColorLinks: "#7D7EAE",
        fontColorDisabled: "#6F6F6F",
        buttonHoverColor: "#FFFFFF",
        fontColorAlert: "#CC615B",
        fontColorSuccess: "#35BD00",
        wrongInvalidColor: "#B33B3B",
    },
    themeId3: {
        primaryColor: "#D2123B",
        secondaryColor: "#D2123B",
        backgroundColor: "#F5F4F4",
        cardBackgroundColor: "#D9D9D9",
        cardItemColor: "#F3F3F3",
        fontColorV1: "#FFFFFF",
        fontColorV2: "#191919",
        fontColorV3: "#8A8A8A",
        fontColorLinks: "#7D7EAE",
        fontColorDisabled: "#6F6F6F",
        buttonHoverColor: "#FFFFFF",
        fontColorAlert: "#CC615B",
        fontColorSuccess: "#35BD00",
        wrongInvalidColor: "#B33B3B",
    },
};

export default themeColorMappings;
