export const GroupEmailFilterTypeToLabel = {
    "END_WITH":     "Terminando em",
    "START_WITH":   "Começando com",
    "CONTAINS":     "Contendo",
    "EQUALS":       "Igual a",
    "MASK":         "Máscara ( * )",
    "REGEX":        "Padrão RegEx",
};

export const GroupTypeToLabel: { [k in Group.Type]: string } = {
    "INSTITUTION":     "Instituição",
    "CAMPUS":          "Campus",
    "COURSE":          "Curso",
    "PROJECT":         "Projeto",
    "CLASSROOM":       "Sala de Aula",
    "MONITORIA":       "Monitoria",
    "LABORATORY":      "Laboratório",
    "ACADEMIC_CENTER": "Centro Acadêmico",
    "DEPARTMENT":      "Departamento",
    "STUDY_GROUP":     "Grupo de Estudos",
    "GROUP_GENERAL": "Grupo Geral",
    "DIRECTORATE": "Diretoria",
    "MANAGEMENT": "Gerência",
    "COORDINATION": "Coordenação",
    "COMPANY_AREA": "Área da Empresa",
    "DEVELOPMENT_TEAM": "Time de Desenvolvimento",
    "INTEREST_GROUP": "Grupo de Interesse",
    "MISCELLANEOUS_SUBJECTS": "Assuntos Diversos",
    "ENTERTAINMENT": "Entretenimento",
};
