export const TypeLinkToLabel: {[k in Link.Type]: string} = {
    "LINK":      "Link",
    "GITHUB":    "GitHub",
    "GIT":       "Git",
    "TWITTER":   "Twitter",
    "WORDPRESS": "Wordpress",
    "TELEGRAM":  "Telegram",
    "INSTAGRAM": "Instagram",
    "REDDIT":    "Reddit",
    "LINKEDIN":  "LinkedIn",
    "DISCORD":   "Discord",
    "PAYPAL":    "Paypal",
    "WHATSAPP":  "Whatsapp",
    "TRELLO":    "Trello",
    "SLACK":     "Slack",
    "SPOTIFY":   "Spotify",
    "YOUTUBE":   "Youtube",
    "SKYPE":     "Skype",
    "STACK":     "Stack Overflow",
    "FACEBOOK":  "Facebook",
};

export const TypeLinkToBootstrapIcon: {[k in Link.Type]: string} = {
    "LINK":      "link-45deg",
    "GITHUB":    "github",
    "GIT":       "git",
    "TWITTER":   "twitter",
    "WORDPRESS": "wordpress",
    "TELEGRAM":  "telegram",
    "INSTAGRAM": "instagram",
    "REDDIT":    "reddit",
    "LINKEDIN":  "linkedin",
    "DISCORD":   "discord",
    "PAYPAL":    "paypal",
    "WHATSAPP":  "whatsapp",
    "TRELLO":    "trello",
    "SLACK":     "slack",
    "SPOTIFY":   "spotify",
    "YOUTUBE":   "youtube",
    "SKYPE":     "skype",
    "STACK":     "stack-overflow",
    "FACEBOOK":  "facebook",
};
